# This is a simple playbook with installation of curl command on UBUNTU linux system
---
- hosts: control
  become: true
  tasks:
    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - curl
