# A more complex playbook where a loadbalancer NGINX is installed and configured to be restrated on CentOS system using YUM pkg
#

---
- hosts: control
  become: true
  tasks:
    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - curl
root@karachi:/work/ansible/playbooks# cat hostname.yml
---
  - hosts: all
    tasks:
    - name: Hostname of all Machines in Network
      command: date
root@karachi:/work/ansible/playbooks# cat loadbalancer.yml
---
- hosts: 192.168.0.21
  become: true
  tasks:
     - name:  Install web component nginx
       yum:   name={{item}} state=present update_cache=yes
       with_items:
           - python-pip
           - python-virtualenv
